### ISSUE TITLE
Error loading local .mbtiles file on mobile

### ISSUE THREAD

**Issue by lxy111222** [josxha/dart_mbtiles#1]
移动端加载本地.mbtiles文件，报SqliteException(14): while opening the database, bad parameter or other API misuse, bad parameter or other API misuse (code 21)

**Comment by josxha** [comment]
Sorry for the late response. Could you post me your code that you used to open the mbtiles database?
Without I don't think I'm able to help you.

很抱歉这么晚才回复。能否把您用来打开 mbtiles 数据库的代码发给我？
否则我想我帮不了你。

**Comment by josxha** [comment]
Closing this issue for now. Please feel free to provide information and I'll reopen it.
